---
settings:
  name: StorageGRID
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação do StorageGRID
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Problemas conhecidos
      url: "/reference-known-issues.html"
  - title: Começar
    entries:
    - title: Descubra os sistemas StorageGRID
      url: "/task-discover-storagegrid.html"
  - title: Gerenciar sistemas StorageGRID
    entries:
    - title: Visualize seus sistemas StorageGRID
      url: "/task-view-storagegrid.html"
    - title: Visualizar e atualizar certificados StorageGRID
      url: "/task-manage-certificates.html"
    - title: Administrar o StorageGRID usando a visualização avançada
      url: "/task-administer-storagegrid.html"
    - title: Use serviços de dados NetApp com StorageGRID
      url: "/task-enable-data-services.html"
    - title: Remover um sistema
      url: "/task-remove-storagegrid.html"
  - title: Conhecimento e suporte
    entries:
    - title: Registre-se para obter suporte
      url: "/task-support-registration.html"
    - title: Obter ajuda
      url: "/task-get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
